# -*- coding: utf-8 -*-
"""Variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snU3LMJwaBa5R8o-wA_q4YgaFbKgbr7X

Variable names: No Quotes
Test/Strings: Quotes Required
Numbers: No Quotes

**Reserved word** in python, also called keywords, are words that have special meaning in the language and cannot be used as variable names, function names or identifiers*.



1. assert
2. async
3. await
4. break
5. class
6. continue
7. def
8. def
9. elif
10. else
11. except
12. finally
13. for
14. from
15. global
16. if
17. import
18. in
19. is
20. lambda
21. nonlocal
22. not
23. or
24. pass
25. raise
26. return
27. try
28. while
29. with
30. yield

***Rules for containg variable in python***

1. Names can contain letters, numbers, and underscore(_)

2. Names cann't start with a number

3. Names are case-sensitive

4. Cannot use python reserved keywords

5. No special characters except underscore

6. Names should be maningful(Not a rule enforced by python, but good practise)

7. Can't have spaces
"""

print("Hello World")

print("I love Python")

print(12345)

Name = "Ceylon Stat"
print(Name)

"""Variable names: no quotes

Text/strings: quotes required

Numbers: no quotes
"""

print("Hello \n World")

print("Hello \n world \n Hello")

a = 25
b = 23

print("First Variable ",a)
print("Second Variable ",b)

"""**Activity 1**

*Create P Letter in python using " * "*
"""

print("*****")
print("*   *")
print("*****")
print("*")
print("*")

"""**Activity 2**

*Print Two Separate Lines in Python*
"""

print("First Name")
print("Last Name")

print("First Name \nLast Name")

"""***Activity 3***

There is a sepearte line "Hello" and "World"

Print "Hello World" in a Single Line in Python
"""

print("Hello", end = " ")
print("World")

"""***Activity 3***

Print a#b#c#d in Python
"""

print("a","b","c","d",sep = "#")

"""**Activity 4**

Insert a Variable into a String in Python
"""

age = 25

print(f"I am years {age} old")

print("I am",age,"years old")

"""***Activity 5***

Print a Statement with Multiple Variables in Python
"""

Language = "Python"
version = 3.11

print("I am learning", Language, "version", version)

print(f"I am learing {Language} version {version}")

your_name = "Kamal"
your_height = "200cm"
your_weight = "70Kg"

print(f"I am {your_name}. My height is {your_height}. My weight is {your_weight}")

print("I am",your_name,". My height is",your_height,". My weight is",your_weight)

"""***Activity 6***

Print a Name with Decorative Lines in Python
"""

print("-"*40)
print("Piyal")
print("-"*40)

print("="*40)
print("Name : Piyal")
print("Your age : 25")
print("="*40)